# docker-compose.dev.yml
version: '3'

services:
  image:
    container_name: crypto-cover-us
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app/crypto-cover-us-volume
    restart: always
    ports:
      - 3000:3000